import { QuizType } from "./QuizListType";

export const quizData: QuizType[] = [
  {
    quizNumber: 1,
    type: "single",
    question: "UX Dizayn prinsiplari kim tomonidan o‘ylab topilgan?",
    options: ["Peter Morwell", "Don Norman", "Steve Jobs", "Jacob Nielsen"],
    correctAnswer: "Don Norman",
  },
  {
    quizNumber: 1,
    type: "single",
    question: "Front-end sohasida eng ko'p ishlatiladigan dasturlash tili?",
    options: ["C++", "Java", "JavaScript", "Python"],
    correctAnswer: "JavaScript",
  },
  {
    quizNumber: 2,
    type: "multi",
    question: "2. Yaxshi UX dizaynerda qanday xususiyatlar bo‘lishi kerak?",
    options: [
      "Chioriyli UI elementlarini chizish",
      "Yaxshi tinglovchi bo‘la olish",
      "Har doim o‘zi tayyorlagan dizayn yechimini eng to‘g‘ri yechim sifatida ko‘ra olish",
      "Muammolarni tushunish va his qila olish",
      "Ochiq fikrlilik",
      "Foydalanuvchilar fikriga quloq solmaslik. Chunki dizayner o‘z sohasining mutaxassisi va u foydalanuvchidan ko‘ra muammolarni yaxshiroq biladi.",
      "Tartibli bo‘lish",
      "Ishni har doim dizayn dasturlarida dizayn chizishdan boshlasl",
      "Muammolarni yechishga intilish",
    ],
    correctAnswer: [
      "Yaxshi tinglovchi bo‘la olish",
      "Muammolarni tushunish va his qila olish",
      "Ochiq fikrlilik",
      "Tartibli bo‘lish",
      "Muammolarni yechishga intilish",
    ],
  },
  {
    type: "single",
    quizNumber: 4,
    question: "JavaScript dasturlash tilida ma'lumotlar turlari 7 ta.",
    options: ["True", "False"],
    correctAnswer: "True",
  },
  // {
  //   quizNumber: 3,
  //   type: "fill",
  //   sentenceParts: [
  //     "Tobacco is full of ",
  //     " substances that cause disease. In areas where the elderly population already ",
  //     " other age groups, the authorities have begun taking action. Increased ",
  //     " is one of the modern world's greatest achievements. The remarkable double act of two ",
  //     " in one family was achieved by Phyllis Powell and her sister, 103-year-old Gladys Glyde. Our local hospital ",
  //     " visitors to one person for each patient. Protecting the environment ",
  //     " everyone. These animals have generally very short ",
  //     " and multiple health problems. Doctors believe the condition is caused by a ",
  //     " defect. Aubrey de Grey maintains that ",
  //     " is caused by seven underlying factors, each of which can, in theory, be countered. At the age of 92, the great master began work on her last major photographic project—stunning portraits of another ",
  //     ".",
  //   ],
  //   options: [
  //     "lifespans",
  //     "genetic",
  //     "restricts",
  //     "outnumbers",
  //     "benefits",
  //     "aging",
  //     "harmful",
  //     "nonagenarian",
  //     "centenarians",
  //     "longevity",
  //   ],
  //   correctOptions: [
  //     "harmful",
  //     "outnumbers",
  //     "longevity",
  //     "centenarians",
  //     "restricts",
  //     "benefits",
  //     "lifespans",
  //     "genetic",
  //     "aging",
  //     "nonagenarian",
  //   ],
  // },
];
